### ISSUE TITLE
Outdated request package dependency with vulnerability

### ISSUE THREAD

**Issue by Enase** [ArkeologeN/pipl#6]
Steps to reproduce:
1. Add pipl npm package to your project by `npm install pipl --save`
2. See warning in console:
```
npm WARN deprecated tough-cookie@0.9.15: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```
**Details:** `tough-cookie` is a dependency of `request` npm.

**How to fix:** Update your `package.json` file: replace `"request": "~2.31.0"` with `"request": "~2.83.0"`.
**PS:** the last request version should be compatible

**Comment by ArkeologeN** [comment]
Hi @Enase, is it possible for you to write a pull request please?

**Comment by Enase** [comment]
@ArkeologeN see https://github.com/ArkeologeN/pipl/pull/7

**Comment by Enase** [comment]
@ArkeologeN 
FYI: You can enable [dependency graph](https://help.github.com/articles/listing-the-packages-that-a-repository-depends-on/) and [review and update vulnerable dependencies in your repository](https://help.github.com/articles/viewing-and-updating-vulnerable-dependencies-in-your-repository/)

**Comment by Enase** [comment]
@ArkeologeN could you publish updated npm package?

**Comment by ArkeologeN** [comment]
@Enase I just did, hope it helps with `0.1.3`

**Comment by Enase** [comment]
@ArkeologeN thanks a lot!

**Comment by Contributorseven** [comment]
All your updates is unregistered and dose not apply to my accounts my network and my names
